// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Paste_CS_NET.Migrations
{
    [DbContext(typeof(PasteDbContext))]
    [Migration("20230307135022_m1")]
    partial class m1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("Paste", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Expiry")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pastes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("de274b65-cb7d-4668-9eee-5a32df269d52"),
                            Content = "Dummy paste",
                            Expiry = new DateTime(2123, 3, 7, 13, 50, 21, 970, DateTimeKind.Unspecified).AddTicks(2927),
                            Language = "Plaintext"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
